### DISCUSSION TITLE
Goodbye! Is displayed on screen and stove randomly shuts off

### DISCUSSION THREAD

**Discussion by jazzmonger** [jazzmonger/wood-pellet-stove-with-TYWE1S-Tuya-chip#19] [General]
Stove randomly turns off and displays this msg.

I've only caught it once doing this when I was standing over it. I witnessed the following:

it was operating normally, then turned off. It started the cooing down phase.
Pipe temp was over 300 and dropped down to 100. As it hit 100, the msg went from cooling down to "Goodbye!" All sensor values at that time:
![586E5219-57A8-45FD-A14A-073A93971573](https://user-images.githubusercontent.com/52110065/202501142-c92962d6-b37d-4510-8bcd-87e0e7816f68.png)
I also reviewed the values at the moment the stove turned off. . I had the stove in P1 mode which is the highest heating mode. 

![13355FB1-26FC-4AB7-AA2E-8ECDC962EEEA](https://user-images.githubusercontent.com/52110065/202506115-a982eeca-4b91-4d8a-a0db-4eacdf73f16a.png)
![4D749B02-E8F5-4FC5-892C-0198BE51D2DF](https://user-images.githubusercontent.com/52110065/202506122-c248ac0d-03dc-4724-8583-7a27ca74387a.png)

I was thinking that when temp protect goes over 100 it shuts the stove down, but it's running now and temp protect well over 100 and it's still on.

![B30BA7F8-0835-46FC-8C34-608265787191](https://user-images.githubusercontent.com/52110065/202517780-6d5c93a9-c2df-4cf5-906c-7bf92e0cc980.png)

I have an automation that looks for this condition and turns it back on. I check several conditions before turning it back on.  If we go on vacation, I'll have to turn the stoves power off as this automation will keep turning it on unless it's disabled.

```
alias: House  wood stove FIX Goodbye error
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.bs_stove_error
    to: "on"
    enabled: true
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - platform: template
    value_template: |-
      {{ states('sensor.esph_house_stove_current_temp')|float(0) +5 <=
        states('sensor.esph_house_stove_set_temp')|float(0) }}
    enabled: false
  - platform: numeric_state
    entity_id: sensor.esph_house_stove_pipe_temp
    below: 101
condition:
  - condition: state
    entity_id: climate.house_wood_pellet_stove
    attribute: hvac_action
    state: "off"
  - condition: state
    entity_id: climate.house_wood_pellet_stove
    attribute: hvac_action
    state: idle
    enabled: false
  - condition: numeric_state
    entity_id: sensor.esph_house_stove_pipe_temp
    below: 101
  - condition: numeric_state
    entity_id: sensor.esph_house_stove_set_temp
    above: 65
action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: heat
    target:
      entity_id: climate.house_wood_pellet_stove
  - service: notify.mobile_app_jeffs_128gb_ipad
    data:
      message: >-
        Stove Error. House Temp={{
        states('sensor.esph_house_stove_current_temp')}}. Set 
        temp={{states('sensor.esph_house_stove_set_temp')}}
  - service: notify.mobile_app_jeffs_iphone_se
    data:
      message: >-
        Stove Error. House Temp={{
        states('sensor.esph_house_stove_current_temp')}}. Set
        temp={{states('esph_house_stove_set_temp')}}
  - service: logbook.log
    data:
      name: Stove error
      message: >-
        .  Current temp ={{ states('sensor.esph_house_stove_current_temp')}}F. 
        - set temp={{states('sensor.esph_house_stove_set_temp')|float(0) }}
mode: single
```
