### DISCUSSION TITLE
Implementing Real time measurement of Exhaust temps

### DISCUSSION THREAD

**Discussion by jazzmonger** [jazzmonger/wood-pellet-stove-with-TYWE1S-Tuya-chip#30] [General]
So after using the stove for a month now, the fire has gone out only a handful of times while on "ultra-low" setting & P3, which is where I now keep it at all times.  Pellet burn/usage is waaay down, and the glass stays clean for much longer.  It turns out it was the constant lighting/re-lighting of the stove that causes the glass to get so much soot.

The reason the stove sometimes goes out is simple:  the exhaust temp sensor only updates once every 60 seconds via the TuyaMCU datapoint update.  That is defined by the factory code in the stoves display MCU, and there is no way to make it update faster.  By the time the burn pot starts to go out, 1 min is too late to stoke the fire and keep it lit.

So, whats required is a near real-time update of the exhaust temp so the stoking routine can be updated as soon as  the exhaust temp detects the fire is going out.  Not a minute or two later, NOW.  

After looking at all the options, since there is no analog input on the TYWE1s chip, the best way to do this looks to be to use a D1 Mini to replace the TYWE1S chip so the analog input can measure the thermocouple voltage and thus infer the real-time exhaust temp.   it turns out that I already did this  here: 
https://github.com/jazzmonger/wood-stove-with-TYWE1S-Tuya-chip/discussions/23

This approach required only 1 extra wire from the main MCU up to the display.  Simple.  And I accomplished it with a standard 4 wire USB cable and a couple of USB jacks that makes the install very clean.  This is the code I'm adding to the main app after watching the exhaust sensor readings in real time:

```
  - platform: adc
    pin: A0
    id: volts_detect  
    name: "Dev Pipe Thermocouple"
    update_interval: 1s
    filters:
      - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 0.02051 -> 392
          - 0.13770 -> 291
          - 0.20508 -> 257
          - 0.41699 -> 189
          - 0.45508 -> 178
          - 0.49609 -> 167                    
          - 0.55469 -> 151   
          - 0.59570 -> 138   
          - 0.62402 -> 129             
          - 0.66309 -> 115   
          - 0.69531 -> 104   
          - 0.71875 -> 93    
```

I'm currently waiting for a level shifting chip to convert all the 5V signals (MCU Auger, UART sniffer, etc) to 3.3v.  I suspect the infrequent Hardware Watchdog reboots Ive seen happen are being caused by this mismatch, even though everywhere you search on Google, its been stated (by the ESPRESIF CEO even) that the D1 Mini can handle 5v signals "no problem".  

more soon...
