### DISCUSSION TITLE
Measuring Pellet Level - ultrasonic and TOF (time of flight) sensors

### DISCUSSION THREAD

**Discussion by jazzmonger** [jazzmonger/wood-pellet-stove-with-TYWE1S-Tuya-chip#36] [General]
I'm going to detail these sensors here. In short, ultrasonic sensors absolutely SUCK when used in a pellet stove hopper.  Heat, vibration, etc make them completely unusable.

The time of flight (TOF) sensors are ROCK solid.

the first one is the ultrasonic sensor... when it works.  About every 2-3 days it required a hard reset of the ESP to start working again.  I bought 5 of these sensors. They ALL had the same problems. Look at how much noise is in the raw trace. Crazy. I tried every filter I could think of.

![5EC8DAF3-6884-4211-981E-1D7D5E2DE66D](https://user-images.githubusercontent.com/52110065/235482636-f4c3ca19-d7c1-4042-a5b1-9e0890654727.png)

This next pic is from the TOF sensor.  Rock solid, no restarts required, always accurate.

![B74DF86E-FF42-409E-AF80-2C18BC733DC7](https://user-images.githubusercontent.com/52110065/235482649-4a4ea27e-904c-4388-98f5-4d724ab94945.jpeg)

Because it is so accurate and the measurements are always repeatable, I was able to successfully write an automation that senses when the level drops below 10% and send an alert to both my phone and Alexa. Alexa nags me once an hour until I fill the pellets.

trying to do this with an ultrasonic sensor is futile. False triggers galore. Just look how much noise is on the trace (when it even works).

Relevant ESPHome code:
```
  - platform: vl53l0x  # <- MUCH more accurate and less noise than Ultrasonic sensors!
    name: "raw pellet level"
    address: 0x29
    long_range: true
    timeout: 200us
    update_interval: 60s
    unit_of_measurement: "m"
    accuracy_decimals: 2
    on_value:
      then:
# Replace 0.4 by the height of hopper. From the sensor to the bottom.
# website to know how to multiply values :https://www.skillsyouneed.com/num/percent-change.html 
        - sensor.template.publish:
            id: ultrasonic_smoothed
            state: !lambda 'return (0.4-x)*(100/0.4);'
# 
  - platform: template
    id: ultrasonic_smoothed
    update_interval: 30s    
    accuracy_decimals: 0     
    unit_of_measurement: "%"
    icon: "mdi:sack-percent"    
    name: "pellet level processed & filtered"
    filters:
      - sliding_window_moving_average:
          window_size: 60
          send_every: 15
```
And an automation that nags & alerts you when the level gets too low
```
- id: '1673870102546'
  alias: House Pellet Stove Pellets LOW
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.house_pellet_level_processed_filtered
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: 15
  condition:
  - condition: numeric_state
    entity_id: sensor.house_pellet_level_processed_filtered
    below: 15
  action:
  - service: notify.alexa_media_shop
    data:
      message: pellet stove in the house needs pellets .  add pellets now
  - service: media_player.volume_set
    data:
      volume_level: 0.7
    target:
      device_id: 0250dc0aecf2399dfd3b5e8833c42e9d
    alias: Volume 70%
  - service: notify.alexa_media_kitchen_original
    data:
      message: pellet stove needs pellets .  add pellets now
  - service: media_player.volume_set
    data:
      volume_level: 0.4
    alias: Volume 40%
    target:
      entity_id: media_player.kitchen_original
  - service: notify.mobile_app_jeff_s
    data:
      message: Pellets Low
  - service: notify.mobile_app_jeffs_128gb_ipad
    data:
      message: House Pellets Low
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - if:
    - condition: numeric_state
      entity_id: sensor.esph_house_stove_pellet_level_smoothed
      below: 20
    then:
    - service: notify.alexa_media_kitchen_original
      data:
        message: pellet stove needs pellets .  add pellets now
    - service: notify.alexa_media_shop
      data:
        message: pellet stove needs pellets .  add pellets now
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - if:
    - condition: numeric_state
      entity_id: sensor.esph_house_stove_pellet_level_smoothed
      below: 20
    then:
    - service: notify.alexa_media_kitchen_original
      data:
        message: pellet stove needs pellets .  add pellets now
    - service: notify.alexa_media_shop
      data:
        message: pellet stove needs pellets .  add pellets now
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - if:
    - condition: numeric_state
      entity_id: sensor.esph_house_stove_pellet_level_smoothed
      below: 30
    then:
    - service: notify.alexa_media_kitchen_original
      data:
        message: pellet stove needs pellets .  add pellets now
    - service: notify.alexa_media_shop
      data:
        message: pellet stove needs pellets .  add pellets now
  mode: single
```

**Comment by stovedoctor** [comment]
Cool 
I have so many honey doos at two homesright now this will be a next year project.

But I would love to chat with you about some other stuff like how to mod dumb pellet boards. 
34 years I have been a pellet stove expert.
thestovedoc.com

**Reply by jazzmonger** [reply]
Well.... my mods to this smart stove are actually applicable to a dumb stove.  I monitor and control pretty much everything related to the auger except the blower fan with one ESP32, and at this point I'm comfortable saying I know about as much as the stove designer about the control system he fumbled through. 

The hardest part is precisely controlling the burn, which is fire and the pellets can be a variable. Precisely Monitoring the exhaust temp is the best indicator of all.

jeff

**Reply by stovedoctor** [reply]
thats the thing I have a bunch of Bad boards from several stoves some just have bad resistors and such. 
but on my personal stove I helped design 16 years ago  it has a dumb board with only 3 set trim settings is the Auger on Time and a Fuel type switch has pre set tweek of combustion air/ fuel feed. 
the new version stoves  have a way to trim adjust the convection blower and Combustion blower. 
I would like a way to adjust the room air and combustion air for each heat setting.
I would also like a way to change the thermostat keep fire cycle to wait time before shutting off. right now its 30 minutes.
but im no electronic engineer. 
<img width="234" alt="Enviro-M55-Omega-Circuit-Board-and-Control-Panel-with-Decal-50-2164" src="https://user-images.githubusercontent.com/60519485/235496409-1843febe-fd72-4461-94bd-e3ee562a419b.png">
<img width="203" alt="Enviro-Circuit-Board-Control-Panel-with-Decal-50-2164" src="https://user-images.githubusercontent.com/60519485/235496857-e8be7e1e-da2d-438b-b6a6-9fc89e43d207.png">

**Comment by jazzmonger** [comment]
I just had a guy in the "Mathmatics" Discord math channel really improve  my pellet level formula - hyper smart guys over there!  Take some measurements, note them and then create a **Lagrange Polynomial formula**.  I know... a mouthful, but not that hard to understand. The Pellet bin is odd shaped on mine and I could never get good readings with my old forumula.

It is dead nuts accurate now!

https://www.wolframalpha.com/input?i=interpolating+polynomial+%7B0.04%2C100%7D%2C%7B0.22%2C50%7D%7B0.5%2C0%7D
```
# Replace 0.4 by the height of hopper. From the sensor to the bottom.
# https://www.dcode.fr/lagrange-interpolating-polynomial
# take  measurements, top, middle and bottom of pellets w/ the TOF sensor.
# x axix is measuerment distance in meters, y is %
# #  interpolating polynomial {0.03,100},{.18,50}{.34,10}{.38,0}
        - sensor.template.publish:
            id: ultrasonic_smoothed
            state: !lambda 'return (-768.049)*x*x*x + (691.244)*x*x - (448.771)*x + (112.862);'
# 
  - platform: template
    id: ultrasonic_smoothed
    update_interval: 10s    
    accuracy_decimals: 0     
    unit_of_measurement: "%"
    icon: "mdi:sack-percent"    
    name: "Pellet Level %"
```

<img width="618" alt="image" src="https://github.com/jazzmonger/wood-pellet-stove-with-TYWE1S-Tuya-chip/assets/52110065/9f60924f-c8ca-43fe-b9b5-a332aad726a1">
