### DISCUSSION TITLE
Smoothing  the temp Sensors

### DISCUSSION THREAD

**Discussion by jazzmonger** [jazzmonger/wood-pellet-stove-with-TYWE1S-Tuya-chip#8] [General]
## 👋 Welcome!
Smoothing sensors discussion

**Comment by jazzmonger** [comment]
The temp sensors in these stoves are VERY inaccurate.  I found it helpful to create a smoothing sensor to get rid of the extremes in temp fluctuations.

<img width="969" alt="image" src="https://user-images.githubusercontent.com/52110065/206490831-473c6991-c2ae-4ec4-aa10-105f08f495b7.png">


you can see a swing of 8 degrees here! Whereas the smoothed line evens it out. The BS error is a binary sensor value of 55 or 60  that track the Goodbye! fix so it graphs easily.  this shows how many times the stove randomly turns itself off.  Its just easy to visualize that way on the graph below the same scale as temps.

The house is around 60 degrees during the night bc my automation reduces the set   temp at 11:30pm.  at 5:30am, I set the stove to P1 and ECO2 because it takes a while for the rest of the house to heat evenly and ECO2 seems to work well in the mornings when its really cold out, as long as the automation kills the stove when it gets too warm.  After an hour or more ( if its 10F outside, it can take 2 hours), the temp in the house has evened out even though the temp at the stove is much higher than set temp.  I monitor temps and when (smoothed temp >= set temp + 3F), I know the room is warm enough.  Then I turn it off  with an "overtemp automation".  This way the stove isn't cycling on and off a dozen or more times while the room regulates to a comfortable temp.  At 11:30am, I set it for ECO1 and P4.

This whole routine saves cycles on the ignitor which only lasted last winter and 2 weeks of this winter and is almost $50 for a new one.  I HIGHLY recommend getting a spare ignitor.  Call the vendor support line and tell them yours is broken BEFORE it dies, which is inevitable.  It took 2 weeks for my new one to get here "overnight".....

```
alias: "House Pellet stove OVER TEMP PROTECTION "
description: ""
trigger:
  - platform: template
    value_template: |2-
              {{ float( states('sensor.stove_current_temp_sensor_smoothed') , 0)
                >=  float( states('sensor.esph_house_stove_set_temp') , 0) +3 }}
condition:
  - condition: template
    value_template: |2-
              {{ float( states('sensor.stove_current_temp_sensor_smoothed') , 0)
                >=  float( states('sensor.esph_house_stove_set_temp') , 0) +3 }}
    alias: Current temp smoothed  >= Set temp +3
  - condition: or
    conditions:
      - condition: state
        entity_id: climate.house_wood_pellet_stove
        attribute: hvac_action
        state: heating
      - condition: state
        entity_id: climate.house_wood_pellet_stove
        attribute: hvac_action
        state: idle
action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: "off"
    target:
      entity_id: climate.house_wood_pellet_stove
    alias: Climate HVAC to OFF
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
mode: queued
max: 10
```
